name: secure-mac

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@main
    - name: build application
      run: make build
